
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pepe
 */
public class PanelIntroducirPregunta extends javax.swing.JPanel {

    /**
     * Creates new form IntroducirPregunta
     */
    
    private VentanaPrincipal ventana;
    private         String respuestaCorrecta;
    private  String[] respuestas;
    private int nivel;
    private Preguntas nuevaPregunta;
    
    
    public PanelIntroducirPregunta(VentanaPrincipal ventana) {
        initComponents();
        this.setBackground(ventana.getGestionPreguntas().getColor());
        this.ventana=ventana;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        textoPregunta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        respuesta2 = new javax.swing.JTextField();
        respuesta3 = new javax.swing.JTextField();
        respuesta4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        respuestaCorrecta1 = new javax.swing.JRadioButton();
        respuestaCorrecta2 = new javax.swing.JRadioButton();
        respuestaCorrecta3 = new javax.swing.JRadioButton();
        respuestaCorrecta4 = new javax.swing.JRadioButton();
        txtNivel = new javax.swing.JTextField();

        jLabel1.setText("Nivel Pregunta");

        jLabel2.setText("Pregunta");

        jLabel3.setText("Respuesta 1");

        jLabel4.setText("Respuesta2");

        jLabel5.setText("Respuesta3");

        jLabel6.setText("Respuesta 4");

        jButton1.setText("Guardar Nueva Prueba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("RespuestaCorrecta");

        buttonGroup2.add(respuestaCorrecta1);
        respuestaCorrecta1.setText("1");

        buttonGroup2.add(respuestaCorrecta2);
        respuestaCorrecta2.setText("2");

        buttonGroup2.add(respuestaCorrecta3);
        respuestaCorrecta3.setText("3");

        buttonGroup2.add(respuestaCorrecta4);
        respuestaCorrecta4.setText("4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(respuestaCorrecta1)
                                .addGap(26, 26, 26)
                                .addComponent(respuestaCorrecta2)
                                .addGap(28, 28, 28)
                                .addComponent(respuestaCorrecta3)
                                .addGap(32, 32, 32)
                                .addComponent(respuestaCorrecta4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(respuesta4)
                                            .addComponent(respuesta3)
                                            .addComponent(respuesta2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textoPregunta)
                                            .addComponent(respuesta1)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(30, 30, 30)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respuestaCorrecta1)
                    .addComponent(jLabel7)
                    .addComponent(respuestaCorrecta2)
                    .addComponent(respuestaCorrecta3)
                    .addComponent(respuestaCorrecta4))
                .addGap(37, 37, 37)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        respuestas = new String[4];
        
        
        respuestas[0] = respuesta1.getText();
        respuestas[1] = respuesta2.getText();
        respuestas[2] = respuesta3.getText();
        respuestas[3] = respuesta4.getText();
        

        respuestaCorrecta();
        
        try{
                            asignarNivel();


        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Debe introducir un numero");
        }catch(ExcepcinMasNivel e){
            JOptionPane.showMessageDialog(null, "El nivel debe de ser entre 1 y 3");
        }
        

        nuevaPregunta = new Preguntas(textoPregunta.getText(),respuestas,respuestaCorrecta,nivel);

        
        
  
        ventana.getGestionPreguntas().getArrayPreguntas().add(nuevaPregunta);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    public void respuestaCorrecta(){
        if(respuestaCorrecta1.isSelected()){
            
            respuestaCorrecta = respuesta1.getText();
            
        }else if(respuestaCorrecta2.isSelected()){
            respuestaCorrecta = respuesta2.getText();
        }else if(respuestaCorrecta3.isSelected()){
            respuestaCorrecta = respuesta3.getText();
        }else if(respuestaCorrecta4.isSelected()){
            respuestaCorrecta = respuesta4.getText();
        }
    }
    
    public void asignarNivel() throws ExcepcinMasNivel,NumberFormatException{ 
        

                    int num =Integer.parseInt(txtNivel.getText());
                    rangoNivel();

    }
    
    public void rangoNivel() throws ExcepcinMasNivel{
        
       if(Integer.parseInt(txtNivel.getText())>3||Integer.parseInt(txtNivel.getText())<0){
           throw new ExcepcinMasNivel("Nivel fuera de rango");
       }else{
           if(Integer.parseInt(txtNivel.getText())==1){
               nivel=1;
           }else if(Integer.parseInt(txtNivel.getText())==2){
               nivel=2;
           }else if(Integer.parseInt(txtNivel.getText())==3){
               nivel=3;
           }
       }
            
        
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField respuesta1;
    private javax.swing.JTextField respuesta2;
    private javax.swing.JTextField respuesta3;
    private javax.swing.JTextField respuesta4;
    private javax.swing.JRadioButton respuestaCorrecta1;
    private javax.swing.JRadioButton respuestaCorrecta2;
    private javax.swing.JRadioButton respuestaCorrecta3;
    private javax.swing.JRadioButton respuestaCorrecta4;
    private javax.swing.JTextField textoPregunta;
    private javax.swing.JTextField txtNivel;
    // End of variables declaration//GEN-END:variables
}
