
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pepe
 */
public class PanelListarPreguntas extends javax.swing.JPanel {

    
          private  DefaultListModel modelo1;
            
          private   VentanaPrincipal ventana;

    
    /**
     * Creates new form ListarPreguntas
     */
    public PanelListarPreguntas(VentanaPrincipal ventana) {
        initComponents();
        
        this.ventana=ventana;
                this.setBackground(ventana.getGestionPreguntas().getColor());

   
        modelo1 = new DefaultListModel();
        
        cargarModeloLista();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        combobox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        jScrollPane1.setViewportView(list1);

        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nivel\t", "Nombre de pregunta", " " }));
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ordenar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoBuscar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_combobox1ActionPerformed

    public void cargarModeloLista(){
        for(int i=0;i<ventana.getGestionPreguntas().getArrayPreguntas().size();i++){

            modelo1.addElement(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta());
       
        }
        
        
        
        list1.setModel(modelo1);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        modelo1.removeAllElements();
        
        
        int seleccion = combobox1.getSelectedIndex();
        
        if(seleccion==0){
            ventana.getGestionPreguntas().ordenarArrayPreguntas();
        }
        else if(seleccion==1){
             ventana.getGestionPreguntas().ordenarArrayListNombrePregunta();
        }
         
         
         
        cargarModeloLista();
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void textoBuscar(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoBuscar
        // TODO add your handling code here:
         modelo1.removeAllElements();
        for(int i=0;i<ventana.getGestionPreguntas().getArrayPreguntas().size();i++){
              
            
                if(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta().contains(txtBuscar.getText())){

                    modelo1.addElement(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta());
                    
                }
              }
        
    }//GEN-LAST:event_textoBuscar

    public void listar(){
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
