
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AYALA
 */
public class PanelBorrarPregunta extends javax.swing.JPanel {

    private  DefaultListModel modelo1;
    private VentanaPrincipal ventana;
    private         Preguntas preguntaSeleccionada;

    
    /**
     * Creates new form PanelBorrarPregunta
     */
    public PanelBorrarPregunta(VentanaPrincipal ventana) {
        initComponents();
        
        this.ventana=ventana;
        
   
        modelo1 = new DefaultListModel();
        
        cargarModeloLista();
        
    }

    public void cargarModeloLista(){
        for(int i=0;i<ventana.getGestionPreguntas().getArrayPreguntas().size();i++){

            modelo1.addElement(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta());
       
        }
        
        list1.setModel(modelo1);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(list1);

        jButton1.setText("Borrar Pregunta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
            if(list1.getSelectedIndex()==-1){
                
               JOptionPane.showMessageDialog(null,"Debe de elegir una pregunta");                                 
    
            }else{
                
                if(ventana.getGestionPreguntas().comprobarNumeroPreguntas()){
                    
                }else{
                    ventana.getGestionPreguntas().getArrayPreguntas().remove(list1.getSelectedIndex());

                     modelo1.remove(list1.getSelectedIndex());
                }

                

                
            }
 

        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list1;
    // End of variables declaration//GEN-END:variables
}
