
import java.applet.AudioClip;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pepe
 */
public class PanelJuego extends javax.swing.JPanel {

    
    private VentanaPrincipal ventana;
    private int contadorPreguntas=0;
    private Image imagen;
    private JRadioButton[] arrayBotones;
    private JRadioButton preguntaCorrecta; 
    private final Object[] opciones={"volver a jugar","pantalla de inicio","salir"};
    private final String cancelar = "cancelar";
    private String comodinFuera = "comodin1Fuera.jpg";
    private AudioClip sonido;
    private Contador reloj;
    /**
     * Creates new form MenuJuego
     */
    public PanelJuego(VentanaPrincipal ventana) {
        initComponents();
        this.ventana=ventana;
        reloj = new Contador(txtTiempo,30,ventana);
        
        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/musica1.wav"));
        comprobarSonido();

        ventana.getAudioClip().stop();
        this.txtNombre.setText(ventana.getGestionPreguntas().getNombreUsuario());
        cambiarNumeroComodines();

            ventana.getGestionPreguntas().ordenarArrayPreguntas();
          
          

                ventana.getGestionPreguntas().arraysPreguntasNivel1();
                ventana.getGestionPreguntas().arraysPreguntasNivel2();
                ventana.getGestionPreguntas().arraysPreguntasNivel3();


                ventana.getGestionPreguntas().rellenaArray1();
                ventana.getGestionPreguntas().rellenaArray2();
                ventana.getGestionPreguntas().rellenaArray3();
                
                ventana.getGestionPreguntas().cargarPregunta(this,this.labelNumeroPregunta,this.labelPregunta,this.radioRespuesta1,this.radioRespuesta2,this.radioRespuesta3,this.radioRespuesta4,contadorPreguntas);

         

          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        grupoBotones = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        radioRespuesta1 = new javax.swing.JRadioButton();
        radioRespuesta2 = new javax.swing.JRadioButton();
        radioRespuesta3 = new javax.swing.JRadioButton();
        radioRespuesta4 = new javax.swing.JRadioButton();
        labelNumeroPregunta = new javax.swing.JLabel();
        labelDinero = new javax.swing.JLabel();
        botonConfirmar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        comodin2 = new javax.swing.JButton();
        comodin3 = new javax.swing.JButton();
        comodin1 = new javax.swing.JButton();
        txtNombre = new javax.swing.JLabel();
        labelComodin1 = new javax.swing.JLabel();
        labelComodin2 = new javax.swing.JLabel();
        labelComodin3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jButton2.setText("jButton2");

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        labelPregunta.setBackground(new java.awt.Color(255, 255, 255));
        labelPregunta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelPregunta.setForeground(new java.awt.Color(255, 255, 255));
        labelPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelPregunta);
        labelPregunta.setBounds(10, 300, 570, 50);

        grupoBotones.add(radioRespuesta1);
        radioRespuesta1.setForeground(new java.awt.Color(255, 255, 255));
        radioRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta1ActionPerformed(evt);
            }
        });
        add(radioRespuesta1);
        radioRespuesta1.setBounds(20, 400, 130, 21);

        grupoBotones.add(radioRespuesta2);
        radioRespuesta2.setForeground(new java.awt.Color(255, 255, 255));
        radioRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta2ActionPerformed(evt);
            }
        });
        add(radioRespuesta2);
        radioRespuesta2.setBounds(160, 400, 130, 21);

        grupoBotones.add(radioRespuesta3);
        radioRespuesta3.setForeground(new java.awt.Color(255, 255, 255));
        radioRespuesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta3ActionPerformed(evt);
            }
        });
        add(radioRespuesta3);
        radioRespuesta3.setBounds(300, 400, 130, 21);

        grupoBotones.add(radioRespuesta4);
        radioRespuesta4.setForeground(new java.awt.Color(255, 255, 255));
        radioRespuesta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRespuesta4ActionPerformed(evt);
            }
        });
        add(radioRespuesta4);
        radioRespuesta4.setBounds(440, 400, 120, 21);

        labelNumeroPregunta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelNumeroPregunta.setForeground(new java.awt.Color(255, 255, 255));
        labelNumeroPregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(labelNumeroPregunta);
        labelNumeroPregunta.setBounds(10, 260, 570, 30);

        labelDinero.setForeground(new java.awt.Color(255, 255, 255));
        labelDinero.setText("0");
        add(labelDinero);
        labelDinero.setBounds(530, 40, 80, 14);

        botonConfirmar.setText("CONFIRMAR");
        botonConfirmar.setEnabled(false);
        botonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConfirmarActionPerformed(evt);
            }
        });
        add(botonConfirmar);
        botonConfirmar.setBounds(450, 180, 120, 23);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DINERO ACUMULADO:");
        add(jLabel3);
        jLabel3.setBounds(400, 40, 150, 14);
        add(barraProgreso);
        barraProgreso.setBounds(20, 430, 540, 14);

        comodin2.setText("COMODIN");
        comodin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comodin2ActionPerformed(evt);
            }
        });
        add(comodin2);
        comodin2.setBounds(20, 140, 90, 23);

        comodin3.setText("COMODIN");
        comodin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comodin3ActionPerformed(evt);
            }
        });
        add(comodin3);
        comodin3.setBounds(20, 100, 90, 23);

        comodin1.setText("COMODIN ");
        comodin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comodin1ActionPerformed(evt);
            }
        });
        add(comodin1);
        comodin1.setBounds(20, 180, 90, 23);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        add(txtNombre);
        txtNombre.setBounds(80, 20, 150, 20);

        labelComodin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comodin1.jpg"))); // NOI18N
        add(labelComodin1);
        labelComodin1.setBounds(20, 50, 30, 30);

        labelComodin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comodin1.jpg"))); // NOI18N
        add(labelComodin2);
        labelComodin2.setBounds(60, 50, 30, 30);

        labelComodin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comodin1.jpg"))); // NOI18N
        add(labelComodin3);
        labelComodin3.setBounds(100, 50, 30, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        add(jLabel4);
        jLabel4.setBounds(20, 20, 60, 17);

        txtTiempo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTiempo.setForeground(new java.awt.Color(255, 0, 51));
        txtTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTiempo.setText("30");
        add(txtTiempo);
        txtTiempo.setBounds(450, 70, 110, 70);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sint_tul22o.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(140, -210, 550, 700);
    }// </editor-fold>//GEN-END:initComponents

    
   
    
    private void botonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarActionPerformed
        // TODO add your handling code here:
        
            radioRespuesta1.setVisible(true);
            radioRespuesta2.setVisible(true);
            radioRespuesta3.setVisible(true);
            radioRespuesta4.setVisible(true);

            botonConfirmar.setEnabled(false);
            
            

            if(respuestaAcertada().isSelected()){
                reloj.reloadReloj();

                                System.out.print(ventana.getGestionPreguntas().getArray15Preguntas()[contadorPreguntas]);

                labelDinero.setText(String.valueOf(ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]));
            
                contadorPreguntas++;

                ventana.getGestionPreguntas().cargarPregunta(this,labelNumeroPregunta, labelPregunta, radioRespuesta1, radioRespuesta2, radioRespuesta3, radioRespuesta4, contadorPreguntas);
                barraProgreso.setValue(barraProgreso.getValue()+6);
            }else{
                
                reloj.pararReloj();
                
                if(ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]<1000){
                                        ventana.getGestionPreguntas().setDineroGanado(0);

                }
                else if(ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]>=1000 &&ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]<8000){
                    ventana.getGestionPreguntas().setDineroGanado(1000);
                }else if(ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]>=8000 &&ventana.getGestionPreguntas().obtenerArrayDinero()[contadorPreguntas]<50000){
                                        ventana.getGestionPreguntas().setDineroGanado(8000);

                }
                
                
                int resultado = JOptionPane.showOptionDialog(this, "Has perdido, te has llevado "+ventana.getGestionPreguntas().getDineroGanado()+"€", "Fallaste", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, cancelar); 
                
                switch (resultado) {
                    case 0:
                       
                       ventana.getGestionPreguntas().borrarArrayListPreguntasPorNivel();
                        
                       ventana.getGestionPreguntas().setJuegoIniciado(true);
                       ventana.getGestionPreguntas().resetearTodosContadores();
                       
                        PanelJuego panel = new PanelJuego(ventana);
                        ventana.getGestionPreguntas().cambiarPanel(ventana, panel);
                        this.validate();
                        break;
                   
                    case 1:
                        
                        ventana.getGestionPreguntas().borrarArrayListPreguntasPorNivel();

                       
                        this.getAudioClip().stop();
                        ventana.getGestionPreguntas().setJuegoIniciado(true);

                        ventana.getGestionPreguntas().resetearTodosContadores();

                        ventana.getBarraMenu().setVisible(true);
                        PanelImagenJFrame panel2 = new PanelImagenJFrame(ventana);
                        ventana.getGestionPreguntas().cambiarPanel(ventana, panel2);
                        break;
                   
                    case 2:
                       
                        System.exit(0);
                    
                    default:
                        break;
                }
                
            }
        
            grupoBotones.clearSelection();
            
            
       
    }//GEN-LAST:event_botonConfirmarActionPerformed

    
    
  
    
    private void comodin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comodin1ActionPerformed
        // TODO add your handling code here:
        
        ventana.getGestionPreguntas().cambiarImagen(labelComodin3, comodinFuera);
        
        
        ventana.getGestionPreguntas().comodin(this);
        comodin1.setEnabled(false);

    }//GEN-LAST:event_comodin1ActionPerformed

    private void comodin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comodin2ActionPerformed
        // TODO add your handling code here:
          ventana.getGestionPreguntas().cambiarImagen(labelComodin2, comodinFuera);
        ventana.getGestionPreguntas().comodin(this);
        comodin2.setEnabled(false);
    }//GEN-LAST:event_comodin2ActionPerformed

    private void comodin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comodin3ActionPerformed
        // TODO add your handling code here:
          ventana.getGestionPreguntas().cambiarImagen(labelComodin1, comodinFuera);
        ventana.getGestionPreguntas().comodin(this);
        comodin3.setEnabled(false);
    }//GEN-LAST:event_comodin3ActionPerformed

    private void radioRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta1ActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setEnabled(true);

    }//GEN-LAST:event_radioRespuesta1ActionPerformed

    private void radioRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta2ActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setEnabled(true);

    }//GEN-LAST:event_radioRespuesta2ActionPerformed

    private void radioRespuesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta3ActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setEnabled(true);

    }//GEN-LAST:event_radioRespuesta3ActionPerformed

    private void radioRespuesta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRespuesta4ActionPerformed
        // TODO add your handling code here:
        botonConfirmar.setEnabled(true);

    }//GEN-LAST:event_radioRespuesta4ActionPerformed

    public JRadioButton getRespuesta1(){
        return radioRespuesta1;
    }
    public JRadioButton getRespuesta2(){
        return radioRespuesta2;
    }
    public JRadioButton getRespuesta3(){
        return radioRespuesta3;
    }
    public JRadioButton getRespuesta4(){
        return radioRespuesta4;
    }
    
    public JRadioButton respuestaAcertada(){
        
        preguntaCorrecta=new JRadioButton();
        
        if( ventana.getGestionPreguntas().getArrayPreguntas().get(ventana.getGestionPreguntas().getArray15Preguntas()[contadorPreguntas]).getRespuestaAcertada().equalsIgnoreCase(getRespuesta1().getText())){
            preguntaCorrecta=getRespuesta1();
        }else if(ventana.getGestionPreguntas().getArrayPreguntas().get(ventana.getGestionPreguntas().getArray15Preguntas()[contadorPreguntas]).getRespuestaAcertada().equalsIgnoreCase(getRespuesta2().getText())){
                        preguntaCorrecta=getRespuesta2();
            

        }else if(ventana.getGestionPreguntas().getArrayPreguntas().get(ventana.getGestionPreguntas().getArray15Preguntas()[contadorPreguntas]).getRespuestaAcertada().equalsIgnoreCase(getRespuesta3().getText())){
                        preguntaCorrecta=getRespuesta3();
            

        }else if(ventana.getGestionPreguntas().getArrayPreguntas().get(ventana.getGestionPreguntas().getArray15Preguntas()[contadorPreguntas]).getRespuestaAcertada().equalsIgnoreCase(getRespuesta4().getText())){
                        preguntaCorrecta=getRespuesta4();
            

        }
  
        return preguntaCorrecta;
        
    }
    
    public void cambiarContadorPreguntas(int contador){
        this.contadorPreguntas=contador;
    }
    
    
    
    public int getContadorPreguntas(){
        return contadorPreguntas;
    }
    
    
    public String getNombrePregunta(){
        return labelPregunta.getText();
    }
    
    public AudioClip getAudioClip(){
        return sonido;
    }
    
    
    public void cambiarNumeroComodines(){
        switch (ventana.getGestionPreguntas().getNumeroComodines()) {
            case 0:
                comodin1.setVisible(false);
                comodin2.setVisible(false);
                comodin3.setVisible(false);
                labelComodin1.setVisible(false);
                labelComodin2.setVisible(false);
                labelComodin3.setVisible(false);
                
                break;
            case 1:
                comodin1.setVisible(false);
                comodin2.setVisible(false);
                labelComodin2.setVisible(false);
                labelComodin3.setVisible(false);
                break;
            case 2:
                comodin1.setVisible(false);
                labelComodin3.setVisible(false);
                break;
            default:
                break;
        }
    }    
    
    public JButton getComodin1(){
        return comodin1;
    }
    public JButton getComodin2(){
        return comodin2;
    }
    public JButton getComodin3(){
        return comodin3;
    }
    
    public void comprobarSonido(){
        if(ventana.getGestionPreguntas().getSonidoApagado()==true){
            sonido.stop();
        }else{
            sonido.play();
        }
    }
   
    
    public JLabel getLabelTiempo(){
        return txtTiempo;
    }
          
    
    public void tiempo(){
        txtTiempo.setText(cancelar);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton botonConfirmar;
    private javax.swing.JButton comodin1;
    private javax.swing.JButton comodin2;
    private javax.swing.JButton comodin3;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelComodin1;
    private javax.swing.JLabel labelComodin2;
    private javax.swing.JLabel labelComodin3;
    private javax.swing.JLabel labelDinero;
    private javax.swing.JLabel labelNumeroPregunta;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JRadioButton radioRespuesta1;
    private javax.swing.JRadioButton radioRespuesta2;
    private javax.swing.JRadioButton radioRespuesta3;
    private javax.swing.JRadioButton radioRespuesta4;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTiempo;
    // End of variables declaration//GEN-END:variables
}