
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pepe
 */
public class PanelModificar extends javax.swing.JPanel {

    
    private  DefaultListModel modelo1;
        private  DefaultListModel modelo2;

    private VentanaPrincipal ventana;
    private  int preguntaSeleccionada;
    private ArrayList<Preguntas> arrayEncontrado;
    private boolean busqueda;
    
    /**
     * Creates new form PanelModificar
     */
    public PanelModificar(VentanaPrincipal ventana) {
        initComponents();
    
        this.ventana=ventana;
                this.setBackground(ventana.getGestionPreguntas().getColor());

   
        modelo1 = new DefaultListModel();
        
        cargarModeloLista();
    
    }
    
    public void cargarModeloLista(){
        
        Iterator<Preguntas> it = ventana.getGestionPreguntas().getArrayPreguntas().iterator();
        
        while(it.hasNext()){
            Preguntas pregunta = it.next();
            
            modelo1.addElement(pregunta.getPregunta());
            
        }
        
        /*for(int i=0;i<ventana.getGestionPreguntas().getArrayPreguntas().size();i++){

            modelo1.addElement(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta());
       
        }*/
        
        list1.setModel(modelo1);
    }
    
    public void buscaPregunta(){
            busqueda=true;
            arrayEncontrado = new ArrayList<Preguntas>();
                                modelo2 = new DefaultListModel();

            for(int i=0;i<ventana.getGestionPreguntas().getArrayPreguntas().size();i++){
              
            
                if(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta().contains(txtBuscar.getText())){

                    arrayEncontrado.add(ventana.getGestionPreguntas().getArrayPreguntas().get(i));
                    modelo2.addElement(ventana.getGestionPreguntas().getArrayPreguntas().get(i).getPregunta());
                    
                }
              }
            
            
            list1.setModel(modelo2);
   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        list1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list1);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscarPregunta(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
         if(list1.getSelectedIndex()==-1){
                
               JOptionPane.showMessageDialog(null,"Debe de elegir una pregunta");                                 
    
            }else{
             
                PanelModificarPreguntaElegida modPregEleg = new PanelModificarPreguntaElegida(ventana,this);
                ventana.getGestionPreguntas().cambiarPanel(ventana, modPregEleg);

                
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void BuscarPregunta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscarPregunta
        // TODO add your handling code here:
        
                buscaPregunta();

        
        
    }//GEN-LAST:event_BuscarPregunta


    public int getPreguntaSeleccionada(){
      
         return  list1.getSelectedIndex();
        
         
    }
    
    public boolean getBusqueda(){
        return busqueda;
    }
    
    public ArrayList<Preguntas> getArrayBusqueda(){
        return arrayEncontrado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
