/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pepe
 */
public class Preguntas extends javax.swing.JPanel implements Comparable<Preguntas>{

    
    private String pregunta;
    private String[] respuesta = new String[4];
    private String respuestaAcertada;
    private int dificultad;
    
    /**
     * Creates new form Preguntas
     */
    public Preguntas(String pregunta,String[] respuesta,String respuestaAcertada,int dificultad) {
        initComponents();
        this.pregunta=pregunta;
        this.respuesta=respuesta;
        this.respuestaAcertada=respuestaAcertada;
        this.dificultad=dificultad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public String getPregunta(){
        return pregunta;
   }
    
   public String[] getRespuesta(){
       return respuesta;
   }
    
   public String getRespuestaAcertada(){
       return respuestaAcertada;
   }
   public int getNivel(){
       return dificultad;
   }
   public void setPregunta(String pregunta){
       this.pregunta=pregunta;
   }
   public void setRespuesta1(String respuesta){
       this.respuesta[0]=respuesta;
   }
   public void setRespuesta2(String respuesta){
       this.respuesta[1]=respuesta;
   }
   public void setRespuesta3(String respuesta){
       this.respuesta[2]=respuesta;
   }
   public void setRespuesta4(String respuesta){
       this.respuesta[3]=respuesta;
   }
   
   public void setDificutad(int dificultad){
       this.dificultad=dificultad;
   }
   
   public void setRespuestaCorrecta(String respuesta){
       this.respuestaAcertada=respuesta;
   }
   
   public String toString(){
       return "Pregunta: "+getPregunta()+"\nRespuestas: "+respuesta[0]+respuesta[1]+respuesta[2]+respuesta[3]+"\nRespuestaCorrecta: "+getRespuestaAcertada()+"\nNivel: "+dificultad;
   }

    @Override
    public int compareTo(Preguntas o) {
        
        if(this.getNivel()!=o.getNivel()){
            return this.getNivel()-o.getNivel();
        }else{
        
        return this.getPregunta().compareTo(o.getPregunta());
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
